name: phys4041
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - ipykernel
  - matplotlib
  - pennylane
  - pip:
    - qiskit
    - qiskit-ibm-runtime
    - qiskit[visulization]
    - pennylane-qiskit
    - torch
    - torchvision
    - jax~=0.6.0
    - jaxlib~=0.6.0
    - optax
    - tensorflow
    - tensorflow-datasets